
/// this class was made using AI. I did reseach on what was needed, and them specified what functions were required. 

using System;
using System.Data;
using Microsoft.Data.SqlClient;

namespace GoalApp.Data
{
    /// Handles communication between the C# application and the SQL database for Goal objects.
    public class ReadWritter
    {
        // Connection string used to connect to the SQL database.
        // IMPORTANT: Replace this with your actual connection information.
        private readonly string _connectionString;

        /// Creates a new GoalDatabase object.
        public ReadWritter(string connectionString)
        {
            // Make sure a connection string was actually provided.
            if (string.IsNullOrWhiteSpace(connectionString))
            {
                throw new ArgumentException(
                    "A database connection string is required.",
                    nameof(connectionString));
            }

            _connectionString = connectionString;
        }

        /// Saves a Goal object to the database.
        public int AddGoal(Goal goal)
        {
            // Prevent null objects from being sent to the database.
            if (goal == null)
            {
                throw new ArgumentNullException(nameof(goal));
            }

            // SQL statement used to insert the goal.
            // Parameters (@Name, @Description, etc.) are used instead of putting the C# values directly into the SQL string. This helps prevent SQL injection and formatting errors.
            const string sql = @"
                INSERT INTO Goals
                (
                    Name,
                    User_ID
                    Streak
                    Description,
                    DueDate
                )
                OUTPUT INSERTED.GoalId
                VALUES
                (
                    @Name,
                    @Description,
                    @DueDate
                );";

            // Create the database connection.
            using SqlConnection connection = new SqlConnection(_connectionString);

            // Create the SQL command.
            using SqlCommand command = new SqlCommand(sql, connection);

            // Add the C# object's values as SQL parameters.
            command.Parameters.Add("@Name", SqlDbType.NVarChar, 100)
                .Value = goal.Name;

            command.Parameters.Add("@Description", SqlDbType.NVarChar, -1)
                .Value = (object?)goal.Description ?? DBNull.Value;

            command.Parameters.Add("@DueDate", SqlDbType.DateTime2)
                .Value = goal.DueDate;

            // Open the connection to the database.
            connection.Open();

            // ExecuteScalar returns the first value from the first row.
            //
            // Because our SQL uses:
            //     OUTPUT INSERTED.GoalId
            //
            // this gives us the ID generated by the database.
            object? result = command.ExecuteScalar();

            if (result == null)
            {
                throw new DataException(
                    "The goal was inserted, but no GoalId was returned.");
            }

            // Convert the database ID to an integer and return it.
            int newGoalId = Convert.ToInt32(result);

            // Keep the C# object synchronized with the database.
            goal.GoalId = newGoalId;

            return newGoalId;
        }
        
        /// Edits an existing Goal in the database.
        /// The GoalId is used to determine which database record to update.
        public void EditGoal(Goal goal)
        {
            // Prevent a null Goal object from being sent to the database.
            if (goal == null)
            {
                throw new ArgumentNullException(nameof(goal));
            }

            // Make sure the Goal has a valid ID. An ID of 0 means that the Goal has probably not been saved to the database yet.
            if (goal.GoalId <= 0)
            {
                throw new ArgumentException(
                    "The Goal must have a valid GoalId before it can be edited.",
                    nameof(goal));
            }

            // SQL statement used to update the existing Goal.
            //
            // The GoalId determines which row will be changed.
            // The other parameters contain the new information.
            const string sql = @"
                UPDATE Goals
                SET
                    Name = @Name,
                    Description = @Description,
                    DueDate = @DueDate
                WHERE GoalId = @GoalId;";

            // Create the database connection.
            using SqlConnection connection =
                new SqlConnection(_connectionString);

            // Create the SQL command.
            using SqlCommand command =
                new SqlCommand(sql, connection);

            // Add the updated Goal information as SQL parameters.
            command.Parameters.Add("@Name", SqlDbType.NVarChar, 100)
                .Value = goal.Name;

            command.Parameters.Add("@Description", SqlDbType.NVarChar, -1)
                .Value = (object?)goal.Description ?? DBNull.Value;

            command.Parameters.Add("@DueDate", SqlDbType.DateTime2)
                .Value = goal.DueDate;

            // Add the GoalId so SQL knows which Goal to update.
            command.Parameters.Add("@GoalId", SqlDbType.Int)
                .Value = goal.GoalId;

            // Open the connection to the database.
            connection.Open();

            // ExecuteNonQuery is used because this SQL command
            // changes existing data but does not return a value.
            int rowsAffected = command.ExecuteNonQuery();

            // If no rows were affected, the GoalId did not exist
            // in the database.
            if (rowsAffected == 0)
            {
                throw new DataException(
                    $"No Goal was found with GoalId {goal.GoalId}.");
            }
        }


        /// Deletes an existing Goal from the database.
        public void DeleteGoal(int goalId)
        {
            // Make sure a valid GoalId was provided.
            if (goalId <= 0)
            {
                throw new ArgumentException(
                    "The GoalId must be greater than 0.",
                    nameof(goalId));
            }

            // SQL statement used to delete the Goal.
            //
            // The parameter prevents the ID from being directly
            // inserted into the SQL string.
            const string sql = @"
        DELETE FROM Goals
        WHERE GoalId = @GoalId;";

            // Create the database connection.
            using SqlConnection connection =
                new SqlConnection(_connectionString);

            // Create the SQL command.
            using SqlCommand command =
                new SqlCommand(sql, connection);

            // Add the GoalId as a SQL parameter.
            command.Parameters.Add("@GoalId", SqlDbType.Int)
                .Value = goalId;

            // Open the connection.
            connection.Open();

            // Execute the DELETE command.
            int rowsAffected = command.ExecuteNonQuery();

            // If no rows were affected, there was no Goal
            // with the specified ID.
            if (rowsAffected == 0)
            {
                throw new DataException(
                    $"No Goal was found with GoalId {goalId}.");
            }
        }
    }
}


public class Read_Writter_Manager
{
    public Read_Writter_Manager()
    {
    }

    public create_goal()
    {
        string connectionString =
    "Server=localhost;Database=GoalDatabase;Trusted_Connection=True;TrustServerCertificate=True;";

        GoalDatabase database = new GoalDatabase(connectionString);

        Goal goal = new Goal
        {
            Name = "Finish C# Project",
            Description = "Complete the database portion of the application.",
            DueDate = new DateTime(2026, 10, 15)
        };

        int goalId = database.AddGoal(goal);

        Console.WriteLine($"Goal saved with ID: {goalId}");
    }

    public edit_goal()
    {

    }

    public delete_goal()
    {

    }

    public create_users_database()
    {

    }

    public delete_users_database()
    {

    }
}

